print("starting")
import llm; print("llm loaded")
import pdf_generator; print("pdf_generator loaded")
import audio_processor; print("audio_processor loaded")
import ddx_retrieval; print("ddx_retrieval loaded")
import behavioral_engine; print("behavioral_engine loaded")
import seed_db; print("seed_db loaded")
import agents.intake_agent; print("intake_agent loaded")
import qr_helper; print("qr_helper loaded")
print("all done")
